---
# tasks file for roles/web

- name: Install web server tools
  dnf:
    name:
      - httpd
      - php
      - php-mysqlnd
      - git
    state: present

- name: Start and enable services
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  loop:
    - httpd

- name: Open HTTP/HTTPS ports in firewalld
  firewalld:
    service: "{{ item }}"
    permanent: yes
    state: enabled
  loop:
    - http
    - https
  notify: Reload firwalld

- name: Allow apache to serve content (SELinux)
  seboolean:
    name: httpd_enabled_homedirs
    state: yes
    persistnet: yes

- name: Clone WordPress for app simulation
  git:
    repo: https://github/com/WordPress/WordPress.git
    dest: /var/www/html/wordpress
    version: master
  becomme_user: apache
