---
# tasks file for roles/web

- name: Install web server tools
  dnf:
    name:
      - httpd
      - php
      - php-mysqlnd
      - git
    state: present

- name: Start and enable Apache
  service:
    name: httpd
    state: started
    enabled: yes

- name: Open HTTP/HTTPS ports in firewalld
  firewalld:
    service: "{{ item }}"
    permanent: yes
    state: enabled
  loop:
    - http
    - https
  notify: Reload firewalld

- name: Allow apache to serve content (SELinux)
  seboolean:
    name: httpd_enable_homedirs
    state: yes
    persistent: yes

- name: Clone WordPress for app simulation
  git:
    repo: https://github.com/WordPress/WordPress.git
    dest: /var/www/html/wordpress
    version: master
  become_user: apache
