---
# tasks file for roles/web
- name: Install web server tools
  dnf:
    name:
      - httpd
      - php
      - php-mysqlnd
      - git
    state: present

- name: Start and enable Apache
  service:
    name: httpd
    state: started
    enabled: yes

- name: Open HTTP/HTTPS ports in firewalld
  firewalld:
    service: "{{ item }}"
    permanent: yes
    state: enabled
  loop:
    - http
    - https
  notify: Reload firewalld

- name: Allow Apache to connect to DB (SELinux)
  seboolean:
    name: httpd_can_network_connect_db
    state: yes
    persistent: yes

# --- CLONE FIRST ---
- name: Clone WordPress (force if needed)
  git:
    repo: https://github.com/WordPress/WordPress.git
    dest: /var/www/html
    force: yes
    version: master
  become_user: apache

# --- THEN FIX PERMISSIONS ---
- name: Set ownership for /var/www/html
  file:
    path: /var/www/html
    owner: apache
    group: apache
    state: directory
    recurse: yes
  become: yes

- name: Set file permissions 644
  command: find /var/www/html -type f -exec chmod 644 {} \;
  become: yes

- name: Set directory permissions 755
  command: find /var/www/html -type d -exec chmod 755 {} \;
  become: yes

- name: Restore SELinux context
  command: restorecon -R /var/www/html
  become: yes

# --- FINALLY CONFIG ---
- name: Configure wp-config.php
  template:
    src: wp-config.php.j2
    dest: /var/www/html/wp-config.php
    owner: apache
    group: apache
    mode: '0644'
  become: yes
  notify: Restart Apache
