---

- name: Apply common setup to all servers
  hosts: all
  become: yes
  roles:
    - common

- name: Configure web server
  hosts: web
  become: yes
  vars:
    wp_db_name: "wp_db"
    wp_db_user: "wp_user"
    wp_db_password: "123456"
    wp_db_host: "192.168.221.130"
  roles:
    - web

- name: Configure the database server
  hosts: database
  become: yes
  roles:
    -  database

- name: Configure monitoring server
  hosts: monitoring
  become: yes
  roles:
    - monitoring

- name: Configure backup server
  hosts: backup
  become: yes
  roles:
    - backup

- name: Configure security server
  hosts: security
  become: yes
  roles:
    - security
