---

- name: Apply common setup to all servers
  hosts: all
  become: yes
  roles:
    - common

- name: Configure web server
  hosts: web
  become: yes
  roles:
    - web

- name: Configure monitoring server
  hosts: database
  become: yes
  roles:
    - database

- name: Configure backup server
  hosts: backup
  become: yes
  roles:
    - backup

- name: Configure security server
  hosts: security
  become: yes
  roles:
    - security
